### ISSUE TITLE
Missing Argon2i support

### ISSUE THREAD

**Issue by jamieburchell** [iusrepo/php74#16]
Hi

It seems that Argon2i support is missing from `php74` but it is present in `php73`:

```
[me@php73 ~]$ php -r "echo PASSWORD_ARGON2I;"
2
```

```
[me@php74 ~]$ php -r "echo PASSWORD_ARGON2I;"
PHP Warning:  Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP) in Command line code on line 1

Warning: Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP) in Command line code on line 1
PASSWORD_ARGON2I
```

Any chance we can get the missing support for php74 repo?

**Comment by jamieburchell** [comment]
Just seen this can be enabled by installing `php74-sodium` although now I'm getting:

`password_hash(): A thread value other than 1 is not supported by this implementation`

Whereas in php73 the thread count at 2 seems to be working without issue.

**Comment by remicollet** [comment]
@jamieburchell FYI   https://github.com/php/php-src/pull/7099  (but doesn't seems to be OK for other dev..., so better to not use the "thread" option)
