### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by kaushalshriyan** [iusrepo/php74#22]
I am facing the below issue while hitting https://repo.ius.io/7/src/packages/p/

```
An error occurred while processing your request.

Reference #30.d5961160.1624319418.82c229 
```

Please comment

**Comment by jeffsheltren** [comment]
Not sure if @carlwgeorge fixed this already, but it's working fine for me at the moment. Are you still seeing issues?

**Comment by kaushalshriyan** [comment]
@jeffsheltren It is working fine now Thanks

**Comment by carlwgeorge** [comment]
Something went wrong with the CDN, but I'm not sure what.  I took a look when it was reported in IRC.  Forcing a refresh on the CDN content seems to have resolved it.
