### ISSUE TITLE
php74 and 7.4.23 repo update?

### ISSUE THREAD

**Issue by mcouillard** [iusrepo/php74#26]
When will the repo be updated to include versions beyond 7.4.21? I see here on github it includes up to 7.4.23, the latest. But the repo is on 21:
https://repo.ius.io/7/x86_64/packages/p/

7.4.23 from 8/26/21
https://www.php.net/ChangeLog-7.php

**Comment by jeffsheltren** [comment]
Hiya, thanks for the report. 7.4.23 is currently in IUS Testing. I'd appreciate your testing of that package. I'm going on vacation on Thursday but plan to push it to IUS Stable tomorrow.

**Comment by jeffsheltren** [comment]
See also https://github.com/iusrepo/php74/pull/25

**Comment by jeffsheltren** [comment]
php74-7.4.23-1.el7.ius has been pushed to IUS stable.
