### ISSUE TITLE
PHP 7.4.24

### ISSUE THREAD

**Issue by jdreese** [iusrepo/php74#28]
I know php74 was just recently updated to 7.4.23. However, 7.4.24 was released on Sep 23, 2021 and included a security fix (https://www.php.net/ChangeLog-7.php#7.4.24). Can php74 be updated to 7.4.24? Thanks.

**Comment by JamesWatsonLNRS** [comment]
There's an [open pull request for 7.4.24](https://github.com/iusrepo/php74/pull/27) 

If you review and help test that, it will speed up the process of getting it into the main repo.

**Comment by jdreese** [comment]
I'm happy to test the RPMS once they're ready. I did find them individually at https://cirrus-ci.com/task/5521213456908288. Will these make it to the testing repo (http://repo.ius.io/testing/7/x86_64/) at some point so they can easily be installed/tested via yum?

**Comment by jeffsheltren** [comment]
Once I merge that PR (going to do so now), the CI system builds new RPMs from the `master` branch. I'll pull those down, sign them, and push them to the Testing repo. Typical time in testing is around 1 week, which can be accelerated by people reporting back positive test results and/or in the case of a critical security issue.
