### ISSUE TITLE
PHP 7.4.24 feedback

### ISSUE THREAD

**Issue by jdreese** [iusrepo/php74#29]
I just wanted to provide some feedback for 7.4.24 which is in testing. I upgraded to the following packages on one of my systems and haven't noticed any issues. Thanks.

php74-cli-7.4.24-1.el7.ius.x86_64
php74-common-7.4.24-1.el7.ius.x86_64
php74-devel-7.4.24-1.el7.ius.x86_64
php74-gd-7.4.24-1.el7.ius.x86_64
php74-json-7.4.24-1.el7.ius.x86_64
php74-ldap-7.4.24-1.el7.ius.x86_64
php74-mbstring-7.4.24-1.el7.ius.x86_64
php74-mysqlnd-7.4.24-1.el7.ius.x86_64
php74-odbc-7.4.24-1.el7.ius.x86_64
php74-pdo-7.4.24-1.el7.ius.x86_64
php74-pecl-imagick-3.4.4-4.el7.ius.x86_64
php74-pecl-mongodb-1.9.1-1.el7.ius.x86_64
php74-pecl-yaml-2.1.0-3.el7.ius.x86_64
php74-process-7.4.24-1.el7.ius.x86_64
php74-soap-7.4.24-1.el7.ius.x86_64
php74-xml-7.4.24-1.el7.ius.x86_64

**Comment by jeffsheltren** [comment]
Thanks for the feedback! I've pushed php74-7.4.24-1.el7.ius to IUS Stable.
