### ISSUE TITLE
PHP 7.4 is not available in IUS

### ISSUE THREAD

**Issue by Nipuna-Sankalpa** [iusrepo/php74#3]
Hi Team.
I just checked the availability of the PHP74 in IUS repository via yum search. but could not find any. Do I have to update repositories before trying this out (yum update)? 
I am not an expert on how this IUS is working. therefore please bear with me if the question is so naive.
Thanks

**Comment by csteini** [comment]
Maybe it is availabe in the testing repo?
But I would also be interested if there is a release date for php74 package on ius master.

**Comment by bgibson710** [comment]
Bump, I don't see 74 available either, and I'd like to skip 7.3 if possible since it looks like you are doing something with 74 :)

**Comment by carlwgeorge** [comment]
https://github.com/iusrepo/wishlist/issues/251
